POST http://localhost:8080/rest_home/statistic/selectById?id=1
Accept: text/html
Content-Type: application/json



###

POST http://localhost:8080/rest_home/statistic/statisticBycriteria
Accept: text/html
Content-Type: application/json

{
  "sexy": "男",
  "beginage": null ,
  "endage": null,
  "beiginattack": null ,
  "endattack": null,
  "limit" : 6
}

###

POST http://localhost:8080/rest_home/statistic/add
Accept: text/html
Content-Type: application/json

{
  "name": "模板病种33xx",
  "symptom": "模板症状3"
}



###
POST http://localhost:8080/rest_home/statistic/update
Accept: text/html
Content-Type: application/json

{
  "id": 2,
  "name": "模板病种4xx",
  "symptom": "模板症状4444"
}


###
POST http://localhost:8080/rest_home/statistic/deleteById?id=4
Accept: text/html
Content-Type: application/json

{
  "code": 233,
  "msg": "success",
  "data": null
}

###

175.24.132.190

###