POST http://localhost:8080/rest_home/diseaseNews/selectById?id=1
Accept: text/html
Content-Type: application/json

###

POST http://localhost:8080/rest_home/diseaseNews/selectAllType
Accept: text/html
Content-Type: application/json

###

POST http://localhost:8080/rest_home/diseaseNews/selectByNews
Accept: text/html
Content-Type: application/json

{
  "title": "demo",
  "type": "demo",
  "beginTime": "2020-4-20 16:39:10",
  "endTime": "2020-4-21 21:39:10"
}

###

POST http://localhost:8080/rest_home/diseaseNews/add
Accept: text/html
Content-Type: application/json


{
  "title": "demoData",
  "type": "demoData",
  "content": "%22+keycmd%3D%22null%22%3E%E5%81%A5%E5%BA%B7%3C%2Fa%3E%E3%80%82%3C%2Fp%3E",
  "createtime": "2020-4-21 16:39:10"
}



###
POST http://localhost:8080/rest_home/diseaseNews/update
Accept: text/html
Content-Type: application/json

{
  "id": 1,
  "title": "demoDataaaa",
  "type": "demottt",
  "content": "demoContencccccccccccccc",
  "createtime": "2020-04-19 16:39:10"
}


###
POST http://localhost:8080/rest_home/diseaseNews/deleteById?id=4
Accept: text/html
Content-Type: application/json

{
  "code": 233,
  "msg": "success",
  "data": null
}

###

175.24.132.190

###